using NetControl4BioMed.Data.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace NetControl4BioMed.Data.Seed
{
    /// <summary>
    /// Represents the seed data for the databases.
    /// </summary>
    public static class Databases
    {
        /// <summary>
        /// Represents the databases to be seeded.
        /// </summary>
        public static ICollection<Database> Seed { get; } = new List<Database>
        {
            new Database
            {
                Id = "d7182750-be72-40be-9ac2-ba62f2fe4172",
                DateTimeCreated = DateTime.UtcNow,
                Name = "DrugBank",
                Description = "The DrugBank database is a comprehensive, freely accessible, online database containing information on drugs and drug targets.",
                IsPublic = false,
                Url = "https://www.drugbank.ca/"
            },
            new Database
            {
                Id = "17bebf9e-6a58-464f-8180-0eb913a27932",
                DateTimeCreated = DateTime.UtcNow,
                Name = "Ensembl",
                Description = "Ensembl genome database project is a joint scientific project between the European Bioinformatics Institute and the Wellcome Trust Sanger Institute. It aims to provide a centralized resource for geneticists, molecular biologists and other researchers studying the genomes of our own species and other vertebrates and model organisms.",
                IsPublic = false,
                Url = "https://www.ensembl.org/index.html"
            },
            new Database
            {
                Id = "11b63176-a16f-434c-8a36-e986460afa13",
                DateTimeCreated = DateTime.UtcNow,
                Name = "HGNC",
                Description = "HGNC (HUGO Gene Nomenclature Committee) is a committee of the Human Genome Organisation (HUGO) that sets the standards for human gene nomenclature. The HGNC approves a unique and meaningful name for every known human gene, based on a query of experts. In addition to the name, which is usually 1 to 10 words long, the HGNC also assigns a symbol (a short group of characters) to every gene.",
                IsPublic = false,
                Url = "https://www.genenames.org/"
            },
            new Database
            {
                Id = "ae5e13e7-62c7-4c57-ad04-cc83db996d5d",
                DateTimeCreated = DateTime.UtcNow,
                Name = "InnateDB",
                Description = "InnateDB is a publicly available database of the genes, proteins, experimentally-verified interactions and signaling pathways involved in the innate immune response of humans, mice and bovines to microbial infection. The database captures an improved coverage of the innate immunity interactome by integrating known interactions and pathways from major public databases together with manually-curated data into a centralised resource.",
                IsPublic = false,
                Url = "https://www.innatedb.com/"
            },
            new Database
            {
                Id = "c7da2735-bd4b-4f1f-a855-a9da130583ee",
                DateTimeCreated = DateTime.UtcNow,
                Name = "KEGG",
                Description = "KEGG (Kyoto Encyclopedia of Genes and Genomes) is a database resource for understanding high-level functions and utilities of the biological system, such as the cell, the organism and the ecosystem, from molecular-level information, especially large-scale molecular datasets generated by genome sequencing and other high-throughput experimental technologies.",
                IsPublic = false,
                Url = "https://www.genome.jp/kegg/"
            },
            new Database
            {
                Id = "4f8e2ba7-691d-476e-b121-7af20b158f96",
                DateTimeCreated = DateTime.UtcNow,
                Name = "NCBI",
                Description = "The National Center for Biotechnology Information (NCBI) is part of the United States National Library of Medicine (NLM), a branch of the National Institutes of Health (NIH). It houses a series of databases relevant to biotechnology and biomedicine and is an important resource for bioinformatics tools and services.",
                IsPublic = false,
                Url = "https://www.ncbi.nlm.nih.gov/"
            },
            new Database
            {
                Id = "19140070-fb5f-46c8-90bc-34084bccdf39",
                DateTimeCreated = DateTime.UtcNow,
                Name = "Omnipath",
                Description = "Omnipath is a comprehensive collection of literature curated human and rodent signaling pathways.",
                IsPublic = false,
                Url = "http://omnipathdb.org/"
            },
            new Database
            {
                Id = "e9027507-fca2-4ecd-b7b9-e8489fd992f3",
                DateTimeCreated = DateTime.UtcNow,
                Name = "SIGNOR",
                Description = "SIGNOR (SIGnaling Network Open Resource), organizes and stores in a structured format signaling information published in the scientific literature.",
                IsPublic = false,
                Url = "https://signor.uniroma2.it/"
            },
            new Database
            {
                Id = "52ac12fc-8a00-475e-9c61-23f4de7cb843",
                DateTimeCreated = DateTime.UtcNow,
                Name = "STRING",
                Description = "STRING (Search Tool for the Retrieval of Interacting Genes/Proteins) is a biological database and web resource of known and predicted protein-protein interactions. It contains information from numerous sources, including experimental data, computational prediction methods and public text collections. It contains information on about 9.6 million proteins. STRING has been developed by a consortium of academic institutions, including Novo Nordisk Foundation Center for Protein Research (CPR), European Molecular Biology Laboratory (EMBL), University of Copenhagen (UCPH), Swiss Institue of Bioinformatics (SIB), Technical University of Dresden (TUD) and University of Zurich (UZH).",
                IsPublic = false,
                Url = "https://string-db.org/"
            },
            new Database
            {
                Id = "39757dcc-80ee-4034-992b-f221df8a71e6",
                DateTimeCreated = DateTime.UtcNow,
                Name = "UniProt",
                Description = "UniProt is a freely accessible database of protein sequence and functional information, many entries being derived from genome sequencing projects. It contains a large amount of information about the biological function of proteins derived from the research literature.",
                IsPublic = false,
                Url = "https://www.uniprot.org/"
            }
        };
    }
}
